apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: catalogue-scaledobject
  namespace: bookstore
spec:
  scaleTargetRef:
    name: catalogue-service-blue
  minReplicaCount: 2
  maxReplicaCount: 8
  pollingInterval: 15
  cooldownPeriod: 30
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "60"