apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: bookstore
type: Opaque
stringData:
  # App database
  app-db-password: flask_pass
  app-database-url: postgresql://appuser:flask_pass@app-db-service:5432/appdb

  # Catalogue database
  catalogue-db-password: flask_pass
  catalogue-database-url: postgresql://catalogueuser:flask_pass@catalogue-db-service:5432/cataloguedb

  # Flask SECRET_KEY
  app-db-password-secret: flask_pass