apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-config
  namespace: bookstore
data:
  FLASK_ENV: "production"
  CATALOGUE_SERVICE_URL: "http://catalogue-service.bookstore.svc.cluster.local:80"
